const detailContent={
 'project-albasri-commercial-group':{en:['Project','Albasri Commercial Group','A focused brand and business development engagement designed to strengthen clarity, presence, and commercial momentum.'],ar:['مشروع','مجموعة البصري التجارية','مشروع علامة وتطوير أعمال صُمم لتعزيز الوضوح والحضور والزخم التجاري.']},
 'project-alfayha-eyewear':{en:['Project','Alfayha Eyewear','A refined identity and customer experience direction for a modern eyewear business.'],ar:['مشروع','نظارات الفيحاء','توجيه لهوية وتجربة عميل راقية لعلامة نظارات عصرية.']},
 'project-viir':{en:['Project','Viir','A distinctive visual system created to make a new idea recognizable and ready to grow.'],ar:['مشروع','فيير','نظام بصري مميز صُمم ليجعل الفكرة الجديدة واضحة وجاهزة للنمو.']},
 'project-zone-restaurant':{en:['Project','Zone Restaurant','A hospitality brand direction that turns atmosphere into a memorable business experience.'],ar:['مشروع','مطعم زون','توجيه لعلامة ضيافة يحوّل الأجواء إلى تجربة أعمال لا تُنسى.']},
 'plan-starter':{en:['Growth Plan','Starter','A focused monthly partnership for businesses ready to build a solid strategic and creative foundation.'],ar:['باقة نمو','البداية','شراكة شهرية مركزة للأعمال المستعدة لبناء أساس استراتيجي وإبداعي قوي.']},
 'plan-standard':{en:['Growth Plan','Standard','An ongoing partnership that connects strategy, execution, and consistent business progress.'],ar:['باقة نمو','القياسية','شراكة مستمرة تربط الاستراتيجية والتنفيذ والتقدم المنتظم للأعمال.']},
 'plan-plus':{en:['Growth Plan','Plus','A high-touch growth partnership for businesses that need a dedicated, multi-disciplinary OOXME team.'],ar:['باقة نمو','بلس','شراكة نمو متقدمة للأعمال التي تحتاج فريق OOXME متخصصًا ومتعدد الخبرات.']},
 'service-business-development':{en:['Service','Business Development','We identify commercial opportunities, shape partnerships, and build the systems that help your business move forward.'],ar:['خدمة','تطوير الأعمال','نحدد الفرص التجارية ونبني الشراكات والأنظمة التي تدفع عملك إلى الأمام.']},
 'service-brand-strategy':{en:['Service','Brand Strategy','A clear point of view for how your business should be positioned, understood, and chosen.'],ar:['خدمة','استراتيجية العلامة','وجهة نظر واضحة لكيفية تموضع عملك وفهمه واختياره.']},
 'service-brand-identity':{en:['Service','Brand Identity','A distinct identity system that gives your business a recognizable presence at every touchpoint.'],ar:['خدمة','هوية العلامة','نظام هوية مميز يمنح عملك حضورًا واضحًا في كل نقطة تواصل.']},
 'service-brand-management':{en:['Service','Brand Management','Ongoing guidance to keep every brand expression clear, consistent, and strategically aligned.'],ar:['خدمة','إدارة العلامة','توجيه مستمر للحفاظ على كل تعبير للعلامة واضحًا ومتسقًا ومتوافقًا استراتيجيًا.']},
 'service-website-design-development':{en:['Service','Website Design & Development','Websites designed to make your value clear and turn attention into meaningful action.'],ar:['خدمة','تصميم وتطوير المواقع','مواقع مصممة لتوضيح قيمتك وتحويل الاهتمام إلى فعل حقيقي.']},
 'service-ui-ux-design':{en:['Service','UI/UX Design','Digital journeys that feel intuitive, purposeful, and built around your audience.'],ar:['خدمة','تصميم تجربة وواجهة المستخدم','رحلات رقمية بديهية وهادفة ومبنية حول جمهورك.']},
 'service-social-media-management':{en:['Service','Social Media Management','A considered social presence that turns everyday communication into brand momentum.'],ar:['خدمة','إدارة وسائل التواصل','حضور اجتماعي مدروس يحوّل التواصل اليومي إلى زخم للعلامة.']},
 'service-content-creation':{en:['Service','Content Creation','Useful, relevant content that gives your business a voice people want to follow.'],ar:['خدمة','صناعة المحتوى','محتوى مفيد وملائم يمنح عملك صوتًا يرغب الناس في متابعته.']},
 'service-photography':{en:['Service','Photography','Photography that captures the character, detail, and value behind your business.'],ar:['خدمة','التصوير الفوتوغرافي','صور تلتقط شخصية عملك وتفاصيله وقيمته.']},
 'service-videography':{en:['Service','Videography','Story-led video that makes your message easier to feel, understand, and remember.'],ar:['خدمة','إنتاج الفيديو','فيديو قائم على القصة يجعل رسالتك أسهل للشعور والفهم والتذكر.']},
 'service-drone-production':{en:['Service','Drone Production','Aerial perspectives that give your spaces, projects, and story a wider point of view.'],ar:['خدمة','إنتاج الدرون','مناظير جوية تمنح مساحاتك ومشاريعك وقصتك رؤية أوسع.']},
 'service-interior-photography':{en:['Service','Interior Photography','Thoughtful interior imagery that communicates atmosphere, scale, and attention to detail.'],ar:['خدمة','تصوير المساحات الداخلية','صور داخلية مدروسة تنقل الأجواء والحجم والاهتمام بالتفاصيل.']},
 'service-product-photography':{en:['Service','Product Photography','Product imagery designed to make quality tangible and buying decisions easier.'],ar:['خدمة','تصوير المنتجات','صور منتجات تجعل الجودة ملموسة وقرار الشراء أسهل.']},
 'service-motion-graphics':{en:['Service','Motion Graphics','Motion systems that give your ideas energy, clarity, and a memorable rhythm.'],ar:['خدمة','الرسوم المتحركة','أنظمة حركة تمنح أفكارك طاقة ووضوحًا وإيقاعًا لا يُنسى.']},
 'service-graphic-design':{en:['Service','Graphic Design','Everyday design assets built to keep your business sharp, clear, and recognizable.'],ar:['خدمة','التصميم الجرافيكي','أصول تصميم يومية تحافظ على عملك حادًا وواضحًا وسهل التمييز.']},
 'service-digital-marketing':{en:['Service','Digital Marketing','Connected digital campaigns that align the right message with the right audience.'],ar:['خدمة','التسويق الرقمي','حملات رقمية مترابطة توصل الرسالة الصحيحة إلى الجمهور المناسب.']},
 'service-seo':{en:['Service','SEO','Search strategy that helps the right people discover your business at the right time.'],ar:['خدمة','تحسين محركات البحث','استراتيجية بحث تساعد الأشخاص المناسبين على اكتشاف عملك في الوقت المناسب.']},
 'service-advertising-campaigns':{en:['Service','Advertising Campaigns','Campaigns built around a clear idea, a focused audience, and measurable movement.'],ar:['خدمة','الحملات الإعلانية','حملات مبنية على فكرة واضحة وجمهور محدد وحركة قابلة للقياس.']},
 'service-ai-integration':{en:['Service','AI Integration','Practical AI systems that improve how your business thinks, works, and grows.'],ar:['خدمة','تكامل الذكاء الاصطناعي','أنظمة ذكاء اصطناعي عملية تحسن طريقة تفكير عملك وعمله ونموه.']},
 'service-business-consultation':{en:['Service','Business Consultation','A focused conversation to identify the next important decision for your business.'],ar:['خدمة','استشارات الأعمال','جلسة مركزة لتحديد القرار المهم التالي لعملك.']},
 consultation:{en:['Consultation','Let’s Build Your Business Together','Book a consultation with OOXME to discuss your business, identify opportunities, and create a clear growth strategy.'],ar:['استشارة','لنبنِ أعمالك معًا','احجز استشارة مع OOXME لمناقشة عملك وتحديد الفرص وبناء استراتيجية نمو واضحة.']}
};
const detailRoot=document.documentElement;
const detailKey=document.body.dataset.detail;
const detail=detailContent[detailKey]||detailContent.consultation;
const detailMenu=document.querySelector('.site-menu');
const detailMenuButton=document.querySelector('.menu-toggle');
const detailLanguageButton=document.querySelector('.language-toggle');
let detailLanguage='en';
try{detailLanguage=localStorage.getItem('ooxme-language')==='ar'?'ar':'en'}catch(error){}
function setDetailLanguage(next){detailLanguage=next;const isArabic=next==='ar';detailRoot.lang=next;detailRoot.dir=isArabic?'rtl':'ltr';document.title=isArabic?'قريبًا — OOXME':'Much More Is Coming — OOXME';document.querySelector('[data-detail-label]').textContent='';document.querySelector('[data-detail-heading]').textContent=isArabic?'المزيد قادم قريبًا':'Much More Is Coming';document.querySelector('[data-detail-description]').textContent=isArabic?'هذه الصفحة قيد التطوير حاليًا. سيتوفر المزيد من المحتوى التفصيلي قريبًا.':'This page is currently under development. More detailed content will be available soon.';detailLanguageButton.setAttribute('aria-label',isArabic?'التبديل إلى الإنجليزية':'Switch to Arabic');document.querySelector('[data-nav-home]').textContent=isArabic?'الرئيسية':'Home';document.querySelector('[data-nav-portfolio]').textContent=isArabic?'المعرض':'Portfolio';try{localStorage.setItem('ooxme-language',next)}catch(error){}}
function setDetailMenu(open){detailMenu.classList.toggle('is-open',open);detailMenuButton.setAttribute('aria-expanded',String(open));document.body.classList.toggle('menu-open',open)}
function observeDetailReveals(){const elements=[...document.querySelectorAll('.text-reveal')];if(!('IntersectionObserver'in window)){elements.forEach((element)=>element.classList.add('is-visible'));return}const observer=new IntersectionObserver((entries)=>entries.forEach((entry)=>entry.target.classList.toggle('is-visible',entry.isIntersecting)),{threshold:.14,rootMargin:'0px 0px -7% 0px'});elements.forEach((element,index)=>{element.style.transitionDelay=`${Math.min(index,5)*65}ms`;observer.observe(element)})}
detailMenuButton.addEventListener('click',()=>setDetailMenu(!detailMenu.classList.contains('is-open')));detailLanguageButton.addEventListener('click',()=>setDetailLanguage(detailLanguage==='en'?'ar':'en'));detailMenu.querySelectorAll('a').forEach((link)=>link.addEventListener('click',()=>setDetailMenu(false)));document.addEventListener('keydown',(event)=>{if(event.key==='Escape')setDetailMenu(false)});detailRoot.classList.add('js');setDetailLanguage(detailLanguage);observeDetailReveals();
