(() => {
  'use strict';
  const root=document.documentElement,page=document.querySelector('.s-page--os'),content=page?.querySelector('.s-page__content'),composer=page?.querySelector('[data-s-composer]'),menu=page?.querySelector('[data-s-composer-menu]'),utilities=page?.querySelector('[data-s-send-utilities]'),add=page?.querySelector('.s-page__add'),input=page?.querySelector('.s-page__composer-input'),submit=page?.querySelector('.s-page__submit'),theme=page?.querySelector('[data-s-utility="theme"]'),language=page?.querySelector('[data-s-utility="language"]'),globalNav=page?.querySelector('[data-os-global-nav]'),sections=[...page?.querySelectorAll('[data-s-major-section]')||[]],storeViewport=page?.querySelector('[data-os-store-viewport]'),storeTrack=page?.querySelector('[data-os-store-track]');
  if(!page||!content||!composer||!menu||!utilities||!add||!input||!submit||!theme||!language||!globalNav||!storeViewport||!storeTrack||sections.length!==4)return;
  const resetOsPosition=()=>{window.scrollTo({top:0,left:0,behavior:'auto'});document.documentElement.scrollTop=0;document.body.scrollTop=0;};
  if('scrollRestoration' in history)history.scrollRestoration='manual';
  try{for(const storage of [sessionStorage,localStorage])for(const key of Object.keys(storage))if(key.startsWith('ooxme-os-'))storage.removeItem(key);}catch(_){/* Storage may be unavailable; position reset still applies. */}
  resetOsPosition();window.addEventListener('pageshow',resetOsPosition,{once:true});window.addEventListener('load',resetOsPosition,{once:true});
  const data={store:[
    {name:'Brand Blueprint',ar:'مخطط العلامة التجارية',category:'Digital Business Tool',categoryAr:'أداة اعمال رقمية',description:'A structured brand planning file for positioning, identity, operations, and growth.',descriptionAr:'ملف منظم لتخطيط تموضع العلامة التجارية وهويتها وعملياتها ونموها.',price:'$29',image:'Reference placeholder',active:true},
    {name:'Project Planner',ar:'مخطط المشروع',category:'Digital File',categoryAr:'ملف رقمي',description:'A practical planning system for organizing projects, tasks, priorities, and execution.',descriptionAr:'نظام عملي لتنظيم المشاريع والمهام والاولويات والتنفيذ.',price:'$19',image:'Reference placeholder',active:true},
    {name:'Business Model Kit',ar:'حزمة نموذج العمل',category:'Business Toolkit',categoryAr:'ادوات اعمال',description:'A structured toolkit for reviewing business models, offers, operations, and growth opportunities.',descriptionAr:'حزمة منظمة لمراجعة نموذج العمل والعروض والعمليات وفرص النمو.',price:'$39',image:'Reference placeholder',active:true},
    {name:'Content System',ar:'نظام المحتوى',category:'Content Toolkit',categoryAr:'ادوات محتوى',description:'A practical framework for planning, organizing, and maintaining consistent brand content.',descriptionAr:'اطار عملي لتخطيط وتنظيم واستمرار محتوى العلامة التجارية.',price:'$24',image:'Reference placeholder',active:true},
    {name:'Custom Brand Pack',ar:'حزمة علامة مخصصة',category:'Custom Product',categoryAr:'منتج مخصص',description:'A tailored set of brand files prepared around your business needs and priorities.',descriptionAr:'مجموعة ملفات علامة تجارية مخصصة حسب احتياجات واولويات عملك.',price:'Custom',image:'Reference placeholder',active:true}
  ],consultation:[['Discount codes','UI only · no current source','Local'],['Business sectors','Engineering · Commercial · Other','3'],['Consultation topics','Brand Management · Business Development · Other','3'],['Available days','Day 1 · Day 2 · Day 3 · Day 4','4'],['Available times','09:00 · 13:00 · 17:00 · 21:00','4'],['Durations','45 · 60 · 90 min · Custom','4'],['Pricing','Summary base price / discount / total','Placeholder']],controls:[['Main','/','Composer menu · primary navigation','Route'],['Brand Management','/bm','Composer menu destination','Route'],['RPN','/rpn','Current route','Route'],['Consultation','/consultation','Composer menu destination','Route'],['Store','/store','Composer menu destination','Route'],['Update','/update','Current route','Route'],['OS','/os','Internal dashboard route','Route']]};
  const copy={en:{internal:'Internal OS',statusTitle:'System status',statusDescription:'Safe connection visibility for the services this site can currently see.',statusFootnote:'Secrets and private values are never rendered.',storeEyebrow:'Store management',storeTitle:'Products',storeDescription:'Local UI architecture based on the current Store catalog.',addProduct:'Add product',consultationEyebrow:'Consultation management',consultationTitle:'Configuration',consultationDescription:'Current booking choices mapped as safe local controls.',addOption:'Add option',controlsEyebrow:'Site controls',controlsTitle:'Interactive map',controlsDescription:'A read-only inventory of current routes, CTAs, and navigation actions.',controlsFootnote:'Control behavior is unchanged in this first OS version.',connected:'Available',configured:'Configured',local:'Local UI',enabled:'Enabled',action:'Edit',close:'Close',cancel:'Cancel',delete:'Delete',save:'Save',currentPrice:'Current Price',newPrice:'New Price',reservedPrice:'Reserved',name:'Name',arabicName:'Arabic name',category:'Category',arabicCategory:'Arabic category',description:'Description',arabicDescription:'Arabic description',image:'Image / reference',day:'Switch to Day Mode',dark:'Switch to Dark Mode',language:'Switch to Arabic',ask:'Ask ooxme',add:'Add context',submit:'Submit question'},ar:{internal:'نظام داخلي',statusTitle:'حالة النظام',statusDescription:'عرض آمن للخدمات التي يستطيع الموقع الحالي رؤيتها.',statusFootnote:'لا يتم عرض الأسرار أو القيم الخاصة.',storeEyebrow:'إدارة المتجر',storeTitle:'المنتجات',storeDescription:'هيكل واجهة محلي مبني على كتالوج المتجر الحالي.',addProduct:'إضافة منتج',consultationEyebrow:'إدارة الاستشارة',consultationTitle:'الإعدادات',consultationDescription:'خيارات الحجز الحالية ممثلة كعناصر تحكم محلية آمنة.',addOption:'إضافة خيار',controlsEyebrow:'عناصر الموقع',controlsTitle:'خريطة التفاعل',controlsDescription:'جرد للصفحات والأزرار وإجراءات التنقل الحالية.',controlsFootnote:'لم يتم تغيير سلوك العناصر في إصدار OS الأول.',connected:'متاح',configured:'مهيأ',local:'واجهة محلية',enabled:'مفعل',action:'تحرير',close:'إغلاق',cancel:'إلغاء',delete:'حذف',save:'حفظ',currentPrice:'السعر الحالي',newPrice:'السعر الجديد',reservedPrice:'محجوز',name:'الاسم',arabicName:'الاسم العربي',category:'الفئة',arabicCategory:'الفئة العربية',description:'الوصف',arabicDescription:'الوصف العربي',image:'الصورة / المرجع',day:'التبديل للوضع النهاري',dark:'التبديل للوضع الليلي',language:'التبديل للإنجليزية',ask:'اسأل اوكسوم',add:'إضافة سياق',submit:'إرسال السؤال'}};
  copy.en.controlsFootnote='Enable / Disable states are managed locally in OS.';
  const pageCards={en:[
    {name:'Main',route:'/',controls:[['Arrow Button 1','Redirect to /update','main-update-1'],['Arrow Button 2','Redirect to /update','main-update-2'],['Arrow Button 3','Redirect to /rpn','main-rpn'],['Book a Consultation','Open the consultation section','main-consultation']]},
    {name:'Brand Management',route:'/bm',controls:[['View','Open Section 2 services','bm-view']]},
    {name:'RPN',route:'/rpn',controls:[['Send Email','Start the referral email action','rpn-email'],['Apply Now','Start the referral application action','rpn-apply-now']]},
    {name:'Consultation',route:'/consultation',controls:[['Send consultation message','Submit the consultation message','consultation-send'],['Apply','Apply the discount code','consultation-apply'],['Pay & Confirm','Confirm and pay for the consultation','consultation-pay'],['Language','Switch the consultation composer language','consultation-language']]},
    {name:'Store',route:'/store',controls:[['View','Open the featured product action','store-featured-view'],['View','Open Project Planner','store-project-view'],['View','Open Business Model Kit','store-model-view'],['View','Open Content System','store-content-view'],['View','Open Custom Brand Pack','store-brand-view'],['Request a Custom Product','Open the custom product request action','store-custom']]},
    {name:'Update',route:'/update',controls:[]}
  ],ar:[
    {name:'الرئيسية',route:'/',controls:[['زر السهم الاول','يوجه الى /update','main-update-1'],['زر السهم الثاني','يوجه الى /update','main-update-2'],['زر السهم الثالث','يوجه الى /rpn','main-rpn'],['احجز استشارة','يفتح قسم الاستشارة','main-consultation']]},
    {name:'إدارة العلامة التجارية',route:'/bm',controls:[['عرض','يفتح خدمات القسم الثاني','bm-view']]},
    {name:'RPN',route:'/rpn',controls:[['إرسال بريد إلكتروني','يبدأ إجراء بريد الإحالة','rpn-email'],['قدم الآن','يبدأ إجراء التقديم للإحالة','rpn-apply-now']]},
    {name:'الاستشارة',route:'/consultation',controls:[['إرسال رسالة الاستشارة','يرسل رسالة الاستشارة','consultation-send'],['تطبيق','يطبق رمز الخصم','consultation-apply'],['الدفع والتأكيد','يؤكد ويدفع للاستشارة','consultation-pay'],['اللغة','يبدل لغة مقدم الاستشارة','consultation-language']]},
    {name:'المتجر',route:'/store',controls:[['عرض','يفتح إجراء المنتج المميز','store-featured-view'],['عرض','يفتح مخطط المشروع','store-project-view'],['عرض','يفتح حزمة نموذج العمل','store-model-view'],['عرض','يفتح نظام المحتوى','store-content-view'],['عرض','يفتح حزمة العلامة المخصصة','store-brand-view'],['اطلب منتجًا مخصصًا','يفتح طلب المنتج المخصص','store-custom']]},
    {name:'التحديث',route:'/update',controls:[]}
  ]};
  data.controls=pageCards.en.map((item)=>[item.name,item.route,'','Route']);
  const status=[['Vercel / deployment','vercel.json and deployment metadata detected','available'],['Static website server','Current root serves pages through server.js','available'],['Database / Neon','Environment configuration present; no active current consumer found','configured']];
  const localized={en:{status:[['Vercel / deployment','vercel.json and deployment metadata detected'],['Static website server','Current root serves pages through server.js'],['Database / Neon','Environment configuration present; no active current consumer found']],booking:{heading:'Booking Details',description:'Current consultation booking information',labels:['Consultation topic','Selected day','Selected time','Selected duration','Base Price','Discount','Total'],values:['Not selected','Not selected','Not selected','Not selected','—','—','—'],reject:'Reject',confirm:'Confirm'},controls:[['Main','/','Composer menu · primary navigation','Route'],['Brand Management','/bm','Composer menu destination','Route'],['RPN','/rpn','Current route','Route'],['Consultation','/consultation','Composer menu destination','Route'],['Store','/store','Composer menu destination','Route'],['Update','/update','Current route','Route'],['OS','/os','Internal dashboard route','Route']]},ar:{status:[['فيرسل / النشر','تم العثور على vercel.json وبيانات النشر'],['خادم الموقع الثابت','المجلد الحالي يخدم الصفحات عبر server.js'],['قاعدة البيانات / نيون','إعدادات البيئة موجودة ولا يوجد مستخدم حالي نشط']],booking:{heading:'تفاصيل الحجز',description:'معلومات الحجز الحالية للاستشارة',labels:['موضوع الاستشارة','اليوم المحدد','الوقت المحدد','المدة المحددة','السعر الأساسي','الخصم','الإجمالي'],values:['غير محدد','غير محدد','غير محدد','غير محدد','—','—','—'],reject:'رفض',confirm:'تأكيد'},controls:[['الرئيسية','/','عنصر القائمة · التنقل الرئيسي','مسار'],['إدارة العلامة التجارية','/bm','وجهة في القائمة','مسار'],['RPN','/rpn','المسار الحالي','مسار'],['الاستشارة','/consultation','وجهة في القائمة','مسار'],['المتجر','/store','وجهة في القائمة','مسار'],['التحديث','/update','المسار الحالي','مسار'],['نظام اوكسوم','/os','مسار لوحة داخلية','مسار']]}};
  const localizedLabels=()=>localized[root.lang==='ar'?'ar':'en'];
  const translateRendered=()=>{const ar=root.lang==='ar',t=localizedLabels();page.querySelectorAll('[data-os-status-track] .s-page__os-status-row').forEach((row,i)=>{const item=t.status[i];if(item){row.querySelector('.s-page__os-row-name').textContent=item[0];row.querySelector('.s-page__os-row-detail').textContent=item[1];}});page.querySelectorAll('[data-os-status-dot]').forEach(dot=>dot.setAttribute('aria-label',ar?'نشط':'Active'));page.querySelectorAll('[data-os-booking-track] .s-page__os-booking-card').forEach(card=>{const b=t.booking;card.querySelector('.s-page__os-item-name').textContent=b.heading;card.querySelector('.s-page__os-item-detail').textContent=b.description;card.querySelectorAll('dt').forEach((n,i)=>n.textContent=b.labels[i]);card.querySelectorAll('dd').forEach((n,i)=>n.textContent=b.values[i]);const reject=card.querySelector('.s-page__os-booking-action:not(.is-confirm)'),confirm=card.querySelector('.s-page__os-booking-action.is-confirm');if(reject)reject.textContent=b.reject;if(confirm)confirm.textContent=b.confirm;});page.querySelectorAll('[data-os-control-row]').forEach((row,i)=>{const item=t.controls[i];if(!item)return;row.querySelector('.s-page__os-item-name').textContent=item[0];const details=row.querySelectorAll('.s-page__os-item-detail');if(details[0])details[0].textContent=`${ar?'الموقع:':'Location:'} ${item[1]}`;if(details[1])details[1].textContent=`${ar?'الوظيفة الحالية:':'Current function:'} ${item[2]} · ${item[3]}`;});page.querySelectorAll('[data-os-image-change]').forEach(n=>n.setAttribute('aria-label',n.closest('[data-os-add-product-card]')?(ar?'إضافة صورة منتج':'Add product image'):(ar?'تغيير صورة المنتج':'Change product image')));if(ar){page.querySelectorAll('[data-os-product-field="name"],[data-os-product-field="description"],[data-os-product-field="category"]').forEach(n=>{const value={name:'Name',description:'Description',category:'Category'}[n.dataset.osProductField];n.placeholder=value;n.setAttribute('aria-label',value);});}const kind=globalNav.dataset.osActiveSection,navText=ar?{status:['السابق','التالي'],product:['السابق','التالي'],booking:['السابق','التالي'],control:['السابق','التالي']}[kind]:null;if(navText){globalNav.querySelector('[data-os-nav-prev]').setAttribute('aria-label',`${navText[0]} ${kind==='status'?'الحالة':kind==='product'?'المنتج':kind==='booking'?'الحجز':'العنصر'}`);globalNav.querySelector('[data-os-nav-next]').setAttribute('aria-label',`${navText[1]} ${kind==='status'?'الحالة':kind==='product'?'المنتج':kind==='booking'?'الحجز':'العنصر'}`);}};
  window.addEventListener('ooxme-language-change',()=>queueMicrotask(translateRendered));
  setTimeout(translateRendered,0);
  const repairRendered=()=>{const ar=root.lang==='ar',t=localizedLabels();page.querySelectorAll('[data-os-status-track] .s-page__os-status-row').forEach((row,i)=>{if(t.status[i]){row.querySelector('.s-page__os-row-name').textContent=t.status[i][0];row.querySelector('.s-page__os-row-detail').textContent=t.status[i][1];}});page.querySelectorAll('[data-os-booking-track] .s-page__os-booking-card').forEach(card=>{const b=t.booking;card.querySelector('.s-page__os-item-name').textContent=b.heading;card.querySelector('.s-page__os-item-detail').textContent=b.description;card.querySelectorAll('dt').forEach((n,i)=>n.textContent=b.labels[i]);card.querySelectorAll('dd').forEach((n,i)=>n.textContent=b.values[i]);const actions=card.querySelector('.s-page__os-booking-actions');if(actions)actions.innerHTML=`<button class="s-page__os-booking-action" type="button">${b.reject}</button><button class="s-page__os-booking-action is-confirm" type="button">${b.confirm}</button>`;});page.querySelectorAll('[data-os-control-row]').forEach((row,i)=>{const item=t.controls[i];if(!item)return;row.querySelector('.s-page__os-item-name').textContent=item[0];const details=row.querySelectorAll('.s-page__os-item-detail');if(details[0])details[0].textContent=`${ar?'الموقع:':'Location:'} ${item[1]}`;if(details[1])details[1].textContent=`${ar?'الوظيفة الحالية:':'Current function:'} ${item[2]} · ${item[3]}`;});page.querySelectorAll('[data-os-image-change]').forEach(n=>n.setAttribute('aria-label',n.closest('[data-os-add-product-card]')?(ar?'إضافة صورة منتج':'Add product image'):(ar?'تغيير صورة المنتج':'Change product image')));if(ar)page.querySelectorAll('[data-os-product-field="name"],[data-os-product-field="description"],[data-os-product-field="category"]').forEach(n=>{const value={name:'Name',description:'Description',category:'Category'}[n.dataset.osProductField];n.placeholder=value;n.setAttribute('aria-label',value);});};
  const repairControlActions=()=>page.querySelectorAll('[data-os-control-row]').forEach(row=>{const button=row.querySelector('[data-os-control-toggle]');if(button)button.textContent=row.classList.contains('is-disabled')?(root.lang==='ar'?'تفعيل':'Enable'):(root.lang==='ar'?'تعطيل':'Disable');});
  const repairNavLabels=()=>{const ar=root.lang==='ar',kind=globalNav.dataset.osActiveSection,names=ar?{status:'الحالة',product:'المنتج',booking:'الحجز',control:'العنصر'}:{status:'status',product:'product',booking:'booking',control:'control'},label=names[kind]||names.control;globalNav.setAttribute('aria-label',ar?'التنقل بين عناصر النظام':'OS carousel navigation');globalNav.querySelector('[data-os-nav-prev]').setAttribute('aria-label',ar?`السابق ${label}`:`Previous ${label}`);globalNav.querySelector('[data-os-nav-next]').setAttribute('aria-label',ar?`التالي ${label}`:`Next ${label}`);const storeSection=page.querySelector('[aria-label="Store Management"]');if(storeSection)storeSection.setAttribute('aria-label',ar?'إدارة المتجر':'Store Management');};
  window.addEventListener('ooxme-language-change',()=>queueMicrotask(repairNavLabels));
  setTimeout(repairNavLabels,0);
  let locked=false,touch=null,sectionTouchOrigin=null,settleTimer=0,menuTimer=0,settledSection=0,pendingSection=0,activeStatus=0,activeProduct=0,activeBooking=0,activeControl=0,editingProduct=false,controlStates={},bookingDrag=null;
  const labels=()=>copy[root.lang==='ar'?'ar':'en'];
  const swipeStep=delta=>(delta<0?1:-1)*(root.lang==='ar'?-1:1);
  const trackPosition=(viewport,track,card,dragOffset=0)=>{const cardRect=card.getBoundingClientRect(),cardCenter=cardRect.left+cardRect.width/2,transform=getComputedStyle(track).transform,trackTranslate=transform&&transform!=='none'?new DOMMatrixReadOnly(transform).m41:0;return viewport.clientWidth/2-(cardCenter-trackTranslate)+dragOffset;};
  const setMenu=open=>{clearTimeout(menuTimer);if(open){composer.style.setProperty('--s-composer-menu-height',`${menu.offsetHeight}px`);menu.classList.add('is-open');utilities.classList.add('is-open');submit.classList.add('is-active');menu.setAttribute('aria-hidden','false');utilities.setAttribute('aria-hidden','false');}else{submit.classList.remove('is-active');menuTimer=setTimeout(()=>{menu.classList.remove('is-open');utilities.classList.remove('is-open');menu.setAttribute('aria-hidden','true');utilities.setAttribute('aria-hidden','true');},60);}};
  const syncStoreCarousel=(dragOffset=0,animate=true)=>{const cards=[...storeTrack.children],card=cards[activeProduct];if(!card)return;storeTrack.classList.toggle('is-dragging',!animate);const position=trackPosition(storeViewport,storeTrack,card,dragOffset);storeTrack.style.transform=`translate3d(${position.toFixed(3)}px,0,0)`;cards.forEach((item,i)=>{item.classList.toggle('is-active',i===activeProduct);item.setAttribute('aria-current',i===activeProduct?'true':'false');});};
  const syncBookingCarousel=(dragOffset=0,animate=true)=>{const viewport=sections[2].querySelector('[data-os-booking-viewport]'),track=sections[2].querySelector('[data-os-booking-track]');if(!viewport||!track)return;const cards=[...track.children],card=cards[activeBooking];if(!card)return;const viewportWidth=bookingDrag?.kind==='booking'&&bookingDrag.viewportWidth||viewport.getBoundingClientRect().width;track.classList.toggle('is-dragging',!animate);const position=trackPosition(viewport,track,card,dragOffset);track.style.transform=`translate3d(${position.toFixed(3)}px,0,0)`;cards.forEach((item,i)=>{item.classList.toggle('is-active',i===activeBooking);item.setAttribute('aria-current',i===activeBooking?'true':'false');});};
  const selectStoreProduct=index=>{const count=page.querySelectorAll('[data-os-product-card]').length;activeProduct=Math.max(0,Math.min(count-1,index));editingProduct=false;syncStoreCarousel();};
  const field=(key,value='',placeholder='',direction='')=>`<input value="${value}" placeholder="${placeholder}" aria-label="${placeholder}" ${direction?`dir="${direction}"`:''} readonly data-os-product-field="${key}" />`;
  const syncInlineCarousel=(viewportRef,trackRef,index,dragOffset=0,animate=true)=>{const viewport=typeof viewportRef==='string'?page.querySelector(viewportRef):viewportRef,track=typeof trackRef==='string'?page.querySelector(trackRef):trackRef,cards=track?[...track.children]:[],safeIndex=Math.max(0,Math.min(cards.length-1,index)),card=cards[safeIndex]||cards[0];if(!viewport||!track||!card)return;cards.forEach((item,i)=>{item.classList.toggle('is-active',i===safeIndex);item.setAttribute('aria-current',i===safeIndex?'true':'false');});track.classList.toggle('is-dragging',!animate);const position=trackPosition(viewport,track,card,dragOffset);track.style.transform=`translate3d(${position.toFixed(3)}px,0,0)`;};
  const syncSectionCarousel=(index,animate=true)=>{const section=sections[index];if(!section)return;if(index===1){syncStoreCarousel(0,animate);return;}if(index===2){syncBookingCarousel(0,animate);return;}const viewport=section.querySelector(index===0?'[data-os-status-list]':'[data-os-controls-list]'),track=section.querySelector(index===0?'[data-os-status-track]':'[data-os-controls-track]');syncInlineCarousel(viewport,track,index===0?activeStatus:activeControl,0,animate);};
  const syncAllSectionCarouselsImmediately=()=>sections.forEach((_,index)=>syncSectionCarousel(index,false));
  const updateSectionNav=(animate=true)=>{const bookingCount=page.querySelectorAll('[data-os-booking-track] .s-page__os-booking-card').length,sectionIndex=active(),kind=['status','store','booking','controls'][sectionIndex],configs={status:[activeStatus,status.length],store:[activeProduct,page.querySelectorAll('[data-os-product-card]').length],booking:[activeBooking,bookingCount],controls:[activeControl,data.controls.length]},[index,count]=configs[kind]||[0,1],previous=globalNav.querySelector('[data-os-nav-prev]'),next=globalNav.querySelector('[data-os-nav-next]'),labelsByKind={status:['status','status'],store:['product','product'],booking:['booking','booking'],controls:['control','control']}[kind]||['item','item'];globalNav.dataset.osActiveSection=kind;globalNav.querySelector('[data-os-nav-count]').textContent=`${index+1} / ${count}`;previous.disabled=index<=0;next.disabled=index>=count-1;previous.setAttribute('aria-label',`Previous ${labelsByKind[0]}`);next.setAttribute('aria-label',`Next ${labelsByKind[1]}`);syncSectionCarousel(sectionIndex,animate);};
  page.addEventListener('pointerdown',e=>{const viewport=e.target.closest('[data-os-store-viewport],[data-os-booking-viewport],[data-os-status-list],[data-os-controls-list]');if(!viewport||e.target.closest('button,input,textarea'))return;const kind=viewport.matches('[data-os-store-viewport]')?'store':viewport.matches('[data-os-booking-viewport]')?'booking':viewport.matches('[data-os-status-list]')?'status':'controls',track=kind==='store'?storeTrack:kind==='booking'?viewport.querySelector('[data-os-booking-track]'):viewport.querySelector(kind==='status'?'[data-os-status-track]':'[data-os-controls-track]'),index=kind==='store'?activeProduct:kind==='booking'?activeBooking:kind==='status'?activeStatus:activeControl,card=track?.children[index];if(!track||!card)return;bookingDrag={id:e.pointerId,kind,startX:e.clientX,delta:0,viewportWidth:viewport.getBoundingClientRect().width,cardWidth:card.offsetWidth,gap:parseFloat(getComputedStyle(track).columnGap)||0};viewport.setPointerCapture?.(e.pointerId);if(kind==='store')syncStoreCarousel(0,false);else if(kind==='booking')syncBookingCarousel(0,false);else syncInlineCarousel(kind==='status'?'[data-os-status-list]':'[data-os-controls-list]',kind==='status'?'[data-os-status-track]':'[data-os-controls-track]',index,0,false);});
  page.addEventListener('pointermove',e=>{if(!bookingDrag||e.pointerId!==bookingDrag.id)return;bookingDrag.delta=e.clientX-bookingDrag.startX;if(bookingDrag.kind==='store')syncStoreCarousel(bookingDrag.delta,false);else if(bookingDrag.kind==='booking')syncBookingCarousel(bookingDrag.delta,false);else syncInlineCarousel(bookingDrag.kind==='status'?'[data-os-status-list]':'[data-os-controls-list]',bookingDrag.kind==='status'?'[data-os-status-track]':'[data-os-controls-track]',bookingDrag.kind==='status'?activeStatus:activeControl,bookingDrag.delta,false);});
  const finishCarouselDrag=e=>{if(!bookingDrag||e.pointerId!==bookingDrag.id)return;const {kind,delta}=bookingDrag;bookingDrag=null;if(Math.abs(delta)>=42){const direction=swipeStep(delta);if(kind==='store')selectStoreProduct(activeProduct+direction);else if(kind==='booking'){activeBooking=Math.max(0,Math.min(1,activeBooking+direction));syncBookingCarousel();}else if(kind==='status'){activeStatus=Math.max(0,Math.min(status.length-1,activeStatus+direction));syncInlineCarousel('[data-os-status-list]','[data-os-status-track]',activeStatus);}else{activeControl=Math.max(0,Math.min(data.controls.length-1,activeControl+direction));syncInlineCarousel('[data-os-controls-list]','[data-os-controls-track]',activeControl);}}else if(kind==='store')syncStoreCarousel();else if(kind==='booking')syncBookingCarousel();else syncInlineCarousel(kind==='status'?'[data-os-status-list]':'[data-os-controls-list]',kind==='status'?'[data-os-status-track]':'[data-os-controls-track]',kind==='status'?activeStatus:activeControl);updateSectionNav();};
  page.addEventListener('pointerup',finishCarouselDrag);page.addEventListener('pointercancel',finishCarouselDrag);
  page.addEventListener('click',e=>{const nav=e.target.closest('[data-os-global-nav]'),button=e.target.closest('[data-os-nav-prev],[data-os-nav-next]');if(!nav||!button||button.disabled)return;const kind=['status','store','booking','controls'][active()],delta=button.matches('[data-os-nav-next]')?1:-1;if(kind==='status'){e.stopImmediatePropagation();activeStatus=Math.max(0,Math.min(status.length-1,activeStatus+delta));syncInlineCarousel('[data-os-status-list]','[data-os-status-track]',activeStatus);updateSectionNav();}else if(kind==='booking'){e.stopImmediatePropagation();activeBooking=Math.max(0,Math.min(1,activeBooking+delta));syncBookingCarousel();updateSectionNav();}else if(kind==='controls'){e.stopImmediatePropagation();activeControl=Math.max(0,Math.min(data.controls.length-1,activeControl+delta));syncInlineCarousel('[data-os-controls-list]','[data-os-controls-track]',activeControl);updateSectionNav();}},true);
  page.addEventListener('click',e=>{const nav=e.target.closest('[data-os-global-nav]'),button=e.target.closest('[data-os-nav-prev],[data-os-nav-next]');if(!nav||!button||button.disabled)return;const kind=['status','store','booking','controls'][active()],delta=button.matches('[data-os-nav-next]')?1:-1;if(kind==='status')activeStatus=Math.max(0,Math.min(status.length-1,activeStatus+delta));if(kind==='store'){selectStoreProduct(activeProduct+delta);updateSectionNav();return;}if(kind==='booking')activeBooking=Math.max(0,Math.min(1,activeBooking+delta));if(kind==='controls')activeControl=Math.max(0,Math.min(data.controls.length-1,activeControl+delta));render();updateSectionNav();});
  const render=()=>{const l=labels();page.querySelectorAll('[data-os-copy]').forEach(n=>{if(l[n.dataset.osCopy])n.textContent=l[n.dataset.osCopy];});page.querySelectorAll('.s-page__composer-menu-label').forEach((n,i)=>{n.textContent=(root.lang==='ar'?['إدارة العلامة التجارية','المعرض','الاستشارة','المتجر','تواصل']:['The Brand Management','The Gallery','The Consultation','The Store','Contact'])[i];});page.querySelector('.s-page__visually-hidden').textContent=l.ask;add.setAttribute('aria-label',l.add);submit.setAttribute('aria-label',l.submit);language.setAttribute('aria-label',l.language);theme.setAttribute('aria-label',root.classList.contains('is-day-mode')?l.dark:l.day);language.classList.toggle('is-active',root.lang==='en');language.setAttribute('aria-pressed',String(root.lang==='en'));
    page.querySelector('[data-os-status-list]').innerHTML=`<div class="s-page__os-item-track" data-os-status-track>${status.map(([name,detail,state])=>`<div class="s-page__os-status-row"><div class="s-page__os-row-top"><span class="s-page__os-row-name">${name}</span><span class="s-page__os-pill ${state==='configured'?'is-amber':''}"></span></div><span class="s-page__os-row-detail">${detail}</span></div>`).join('')}</div>`;
    const productCard=(p,i)=>`<article class="s-page__store-card s-page__store-product-card ${i===activeProduct?'is-active':''} ${editingProduct&&i===activeProduct?'is-editing':''}" data-os-product-card data-product-index="${i}" aria-current="${i===activeProduct?'true':'false'}"><div class="s-page__store-image-placeholder"><img class="s-page__os-product-image" src="${p.imageUrl||''}" alt="" ${p.imageUrl?'':'hidden'} /><span class="s-page__os-status-dot ${p.active===false?'is-inactive':''}" aria-label="${p.active===false?'Inactive':'Active'}"></span><button class="s-page__os-image-change" type="button" data-os-image-change aria-label="Change product image">+</button><input class="s-page__os-image-input" type="file" accept="image/*" data-os-image-input /></div><div class="s-page__store-card-copy"><div class="s-page__os-field-grid">${field('name',p.name,l.name)}${field('ar',p.ar,l.arabicName,'rtl')}${field('category',p.category,l.category)}${field('categoryAr',p.categoryAr,l.arabicCategory,'rtl')}${field('description',p.description,l.description)}${field('descriptionAr',p.descriptionAr,l.arabicDescription,'rtl')}</div><div class="s-page__os-price-grid">${field('price',p.price,l.currentPrice)}${field('newPrice',p.price,l.newPrice)}${field('reservedPrice','—',l.reservedPrice)}</div><div class="s-page__os-action-row"><button type="button" data-os-close>${editingProduct&&i===activeProduct?l.cancel:l.close}</button><button type="button" data-os-delete>${l.delete}</button><button type="button" data-os-edit-product>${editingProduct&&i===activeProduct?l.save:l.action}</button></div></div></article>`;
    const emptyIndex=data.store.length;const empty=`<article class="s-page__store-card s-page__store-product-card s-page__os-empty-product-card ${emptyIndex===activeProduct?'is-active':''} ${editingProduct&&emptyIndex===activeProduct?'is-editing':''}" data-os-product-card data-os-add-product-card data-product-index="${emptyIndex}" aria-current="${emptyIndex===activeProduct?'true':'false'}"><div class="s-page__store-image-placeholder"><span class="s-page__os-status-dot is-inactive" aria-hidden="true"></span><button class="s-page__os-image-change" type="button" data-os-image-change aria-label="Add product image">+</button><input class="s-page__os-image-input" type="file" accept="image/*" data-os-image-input /></div><div class="s-page__store-card-copy"><div class="s-page__os-field-grid">${field('name','',l.name)}${field('ar','',l.arabicName,'rtl')}${field('category','',l.category)}${field('categoryAr','',l.arabicCategory,'rtl')}${field('description','',l.description)}${field('descriptionAr','',l.arabicDescription,'rtl')}</div><div class="s-page__os-price-grid">${field('price','',l.currentPrice)}${field('newPrice','',l.newPrice)}${field('reservedPrice','',l.reservedPrice)}</div><div class="s-page__os-action-row"><button type="button" data-os-close>${editingProduct&&activeProduct===emptyIndex?l.cancel:l.close}</button><button type="button" data-os-delete>${l.delete}</button><button type="button" data-os-edit-product>${editingProduct&&activeProduct===emptyIndex?l.save:l.action}</button></div></div></article>`;storeTrack.innerHTML=empty+data.store.map(productCard).join('');syncStoreCarousel();
    const bookingCard=`<article class="s-page__os-booking-card"><div class="s-page__os-booking-heading"><span class="s-page__os-item-name">Booking Details</span><span class="s-page__os-item-detail">Current consultation booking information</span></div><dl class="s-page__os-booking-details"><div><dt>Consultation topic</dt><dd>Not selected</dd></div><div><dt>Selected day</dt><dd>Not selected</dd></div><div><dt>Selected time</dt><dd>Not selected</dd></div><div><dt>Selected duration</dt><dd>Not selected</dd></div><div><dt>Base Price</dt><dd>—</dd></div><div><dt>Discount</dt><dd>—</dd></div><div><dt>Total</dt><dd>—</dd></div></dl><div class="s-page__os-booking-actions"><button class="s-page__os-booking-action" type="button">Reject</button><button class="s-page__os-booking-action is-confirm" type="button">Confirm</button></div></article>`;page.querySelector('[data-os-consultation-list]').innerHTML='<div class="s-page__os-booking-carousel" data-os-booking-carousel><div class="s-page__os-booking-viewport" data-os-booking-viewport><div class="s-page__os-booking-track" data-os-booking-track>'+bookingCard+bookingCard+'</div></div></div>';syncBookingCarousel();page.querySelector('[data-os-controls-list]').innerHTML=`<div class="s-page__os-item-track" data-os-controls-track>${data.controls.map(([name,route,detail,type])=>{const key=`${name}|${route}`,enabled=controlStates[key]!==false;return `<div class="s-page__os-item s-page__os-control-item ${enabled?'':'is-disabled'}" data-os-control-row="${key}"><div class="s-page__os-item-main"><span class="s-page__os-item-name">${name}</span><span class="s-page__os-item-detail">Location: ${route}</span><span class="s-page__os-item-detail">Current function: ${detail} · ${type}</span></div><button class="s-page__os-item-action" type="button" data-os-control-toggle data-os-control-key="${key}" aria-pressed="${!enabled}">${enabled?'Disable':'Enable'}</button></div>`;}).join('')}</div>`;};
  const applyLanguage=(next,{persist=true,emit=true}={})=>{const languageCode=next==='ar'?'ar':'en';root.lang=languageCode;root.dir=languageCode==='ar'?'rtl':'ltr';input.lang=languageCode;input.dir=languageCode==='ar'?'rtl':'ltr';if(persist)try{localStorage.setItem('ooxme-language',languageCode);}catch(_){}render();syncAllSectionCarouselsImmediately();updateSectionNav(false);if(emit)window.dispatchEvent(new CustomEvent('ooxme-language-change',{detail:{language:languageCode}}));};
  window.addEventListener('ooxme-language-change',e=>{const next=e.detail?.language;if(next&&next!==root.lang)applyLanguage(next,{persist:false,emit:false});});
  const normalizeControlCards=()=>{const current=root.lang==='ar'?'ar':'en',items=localized[current].controls;page.querySelectorAll('[data-os-control-row]').forEach((row,i)=>{const item=items[i]||data.controls[i];if(!item)return;const key=`${data.controls[i][0]}|${data.controls[i][1]}`,enabled=controlStates[key]!==false;row.className=`s-page__os-item s-page__os-control-item ${enabled?'':'is-disabled'}`;row.innerHTML=`<div class="s-page__os-page-card-content"><div class="s-page__os-page-heading"><span class="s-page__os-page-name">${item[0]}</span><a class="s-page__os-page-route" href="${item[1]}">${item[1]}</a></div><div class="s-page__os-function-group"><div class="s-page__os-function-copy"><span class="s-page__os-function-name">${item[3]}</span><span class="s-page__os-function-detail">${item[2]}</span></div><button class="s-page__os-item-action" type="button" data-os-control-toggle data-os-control-key="${key}" aria-pressed="${!enabled}">${enabled?(current==='ar'?'تعطيل':'Disable'):(current==='ar'?'تفعيل':'Enable')}</button></div><div class="s-page__os-control-divider" aria-hidden="true"></div></div>`;row.dir=current==='ar'?'rtl':'ltr';row.lang=current;});};
  const normalizePageCards=()=>{const current=root.lang==='ar'?'ar':'en',items=pageCards[current],urlCopy=current==='ar'?'الرابط':'URL',urlDescription=current==='ar'?'يفتح الصفحة':'Open the page';page.querySelectorAll('[data-os-control-row]').forEach((row,i)=>{const item=items[i];if(!item)return;const keyFor=(control)=>`${item.route}|${control[2]}`,allControls=[[urlCopy,`${urlDescription} ${item.name}`,`url-${item.route}`],...item.controls],buttonLabel=control=>controlStates[keyFor(control)]===false?(current==='ar'?'تفعيل':'Enable'):(current==='ar'?'تعطيل':'Disable'),controls=allControls.map((control,index)=>`<div class="s-page__os-page-control"><div class="s-page__os-function-copy"><span class="s-page__os-function-name">${control[0]}</span><span class="s-page__os-function-detail">${control[1]}</span></div><button class="s-page__os-item-action" type="button" data-os-control-toggle data-os-control-key="${keyFor(control)}" aria-pressed="${controlStates[keyFor(control)]===false}">${buttonLabel(control)}</button>${index<allControls.length-1?'<div class="s-page__os-control-divider" aria-hidden="true"></div>':''}</div>`).join('');row.className='s-page__os-item s-page__os-control-item';row.innerHTML=`<div class="s-page__os-page-card-content"><div class="s-page__os-page-heading"><span class="s-page__os-page-name">${item.name}</span><a class="s-page__os-page-route" href="${item.route}">${item.route==='/'?'ooxme.com/':`ooxme.com${item.route}`}</a></div><div class="s-page__os-page-controls">${controls}</div></div>`;row.dir=current==='ar'?'rtl':'ltr';row.lang=current;});};
  window.addEventListener('ooxme-language-change',()=>queueMicrotask(normalizePageCards));
  setTimeout(normalizePageCards,0);
  const legacyControlShape=()=>page.querySelectorAll('[data-os-control-row]').forEach(row=>{const name=row.querySelector('.s-page__os-page-name');if(name)name.classList.add('s-page__os-item-name');const copy=row.querySelector('.s-page__os-function-copy');if(copy&&!copy.querySelector('[data-os-legacy-detail]')){const legacy=document.createElement('span');legacy.dataset.osLegacyDetail='';legacy.className='s-page__os-item-detail';legacy.hidden=true;copy.prepend(legacy);}});
  const controlsList=page.querySelector('[data-os-controls-list]');
  new MutationObserver(()=>{if(!controlsList.querySelector('.s-page__os-page-card-content'))normalizePageCards();}).observe(controlsList,{childList:true,subtree:true});
  const sectionReferenceY=()=>parseFloat(getComputedStyle(content).paddingTop)||0;
  const active=()=>settledSection;
  const resetSectionCarousel=index=>{if(index===0)activeStatus=0;else if(index===1)activeProduct=0;else if(index===2)activeBooking=0;else if(index===3)activeControl=0;};
  const settleSectionTransition=()=>{if(!locked)return;clearTimeout(settleTimer);const correction=sections[pendingSection].getBoundingClientRect().top-sectionReferenceY();if(Math.abs(correction)>.5)window.scrollTo({top:window.scrollY+correction,left:0,behavior:'auto'});settledSection=pendingSection;locked=false;root.classList.add('s-x-initializing');updateSectionNav(false);requestAnimationFrame(()=>root.classList.remove('s-x-initializing'));};
  const scheduleSectionSettle=()=>{if(!locked)return;clearTimeout(settleTimer);settleTimer=setTimeout(settleSectionTransition,120);};
  window.addEventListener('scroll',scheduleSectionSettle,{passive:true});
  window.addEventListener('scrollend',settleSectionTransition,{passive:true});
  const move=dir=>{if(locked)return;const target=Math.max(0,Math.min(sections.length-1,active()+dir));if(target===active())return;locked=true;pendingSection=target;root.classList.add('s-x-initializing');resetSectionCarousel(target);syncSectionCarousel(target,false);window.scrollTo({top:window.scrollY+sections[target].getBoundingClientRect().top-sectionReferenceY(),left:0,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});if(matchMedia('(prefers-reduced-motion: reduce)').matches)requestAnimationFrame(settleSectionTransition);};
  const setEditable=(card,editable)=>{card.querySelectorAll('[data-os-product-field]').forEach(n=>n.readOnly=!editable);card.classList.toggle('is-editing',editable);};
  document.addEventListener('touchstart',e=>{if(e.target.closest('[data-s-composer]'))return;const point=e.changedTouches[0];if(point)sectionTouchOrigin={id:point.identifier,x:point.clientX,y:point.clientY};},{capture:true,passive:true});
  document.addEventListener('touchmove',e=>{const point=[...e.changedTouches].find(item=>item.identifier===sectionTouchOrigin?.id);if(!point)return;if(Math.abs(point.clientY-sectionTouchOrigin.y)>Math.abs(point.clientX-sectionTouchOrigin.x))e.preventDefault();},{capture:true,passive:false});
  document.addEventListener('touchend',e=>{if([...e.changedTouches].some(item=>item.identifier===sectionTouchOrigin?.id))sectionTouchOrigin=null;},{capture:true,passive:true});
  document.addEventListener('touchcancel',()=>{sectionTouchOrigin=null;},{capture:true,passive:true});
  page.addEventListener('click',e=>{const toggle=e.target.closest('[data-os-control-toggle]');if(!toggle)return;const key=toggle.dataset.osControlKey,enabled=controlStates[key]!==false;controlStates[key]=!enabled;const row=toggle.closest('[data-os-control-row]');row.classList.toggle('is-disabled',enabled);toggle.textContent=enabled?(root.lang==='ar'?'تفعيل':'Enable'):(root.lang==='ar'?'تعطيل':'Disable');toggle.setAttribute('aria-pressed',String(enabled));});
  const saveCard=card=>{const fields=Object.fromEntries([...card.querySelectorAll('[data-os-product-field]')].map(n=>[n.dataset.osProductField,n.value])),index=Number(card.dataset.productIndex),imageUrl=card.dataset.pendingImageUrl;if(index===data.store.length){if(!fields.name?.trim()){editingProduct=false;render();return;}data.store.push({name:fields.name,ar:fields.ar,category:fields.category,categoryAr:fields.categoryAr,description:fields.description,descriptionAr:fields.descriptionAr,price:fields.newPrice||fields.price||'Custom',image:'Reference placeholder',imageUrl,active:true});activeProduct=data.store.length;}else{const p=data.store[index];p.name=fields.name;p.ar=fields.ar;p.category=fields.category;p.categoryAr=fields.categoryAr;p.description=fields.description;p.descriptionAr=fields.descriptionAr;p.price=fields.newPrice||fields.price||p.price;if(imageUrl)p.imageUrl=imageUrl;}editingProduct=false;render();};
  composer.addEventListener('submit',e=>{e.preventDefault();setMenu(!menu.classList.contains('is-open'));});add.addEventListener('click',e=>{e.stopPropagation();setMenu(false);});theme.addEventListener('click',e=>{e.stopPropagation();root.classList.toggle('is-day-mode');render();});language.disabled=true;language.setAttribute('aria-label','English only');language.setAttribute('aria-pressed','true');page.addEventListener('input',e=>{if(e.target.matches('[data-os-product-field]')&&editingProduct)e.target.closest('[data-os-product-card]').querySelector('[data-os-edit-product]').textContent=labels().save;});page.addEventListener('click',e=>{const card=e.target.closest('[data-os-product-card]');if(!card)return;const index=Number(card.dataset.productIndex);if(e.target.closest('[data-os-image-change]')){if(!card.classList.contains('is-editing'))return;card.querySelector('[data-os-image-input]').click();return;}if(e.target.matches('[data-os-image-input]'))return;if(e.target.closest('[data-os-edit-product]')){if(editingProduct&&card===page.querySelector(`[data-product-index="${activeProduct}"]`))saveCard(card);else{selectStoreProduct(index);editingProduct=true;setEditable(card,true);card.querySelector('[data-os-edit-product]').textContent=labels().save;}}if(e.target.closest('[data-os-close]')){if(editingProduct){editingProduct=false;render();}else if(index<data.store.length){data.store[index].active=false;render();}}if(e.target.closest('[data-os-delete]'))e.preventDefault();});page.addEventListener('change',e=>{if(!e.target.matches('[data-os-image-input]'))return;const file=e.target.files?.[0],card=e.target.closest('[data-os-product-card]');if(!file||!card)return;const image=card.querySelector('.s-page__os-product-image');image.src=URL.createObjectURL(file);image.hidden=false;card.dataset.pendingImageUrl=image.src;card.querySelector('[data-os-edit-product]').textContent=labels().save;});
  page.querySelector('[data-s-menu-brand]').addEventListener('click',()=>window.location.assign('/bm'));document.addEventListener('pointerdown',e=>{if(!composer.contains(e.target))setMenu(false);},{passive:true});document.addEventListener('touchstart',e=>{if(e.target.closest('[data-s-composer]'))return;const i=e.changedTouches[0];if(i)touch={id:i.identifier,y:i.clientY};},{capture:true,passive:true});document.addEventListener('touchend',e=>{const i=[...e.changedTouches].find(x=>x.identifier===touch?.id);if(i&&Math.abs(i.clientY-touch.y)>=36)move(i.clientY<touch.y?1:-1);touch=null;},{capture:true,passive:true});window.addEventListener('wheel',e=>{e.preventDefault();if(Math.abs(e.deltaY)>=8)move(e.deltaY>0?1:-1);},{passive:false});window.addEventListener('keydown',e=>{if(![' ','ArrowDown','ArrowUp','PageDown','PageUp','Home','End'].includes(e.key)||e.target.closest('input,textarea'))return;e.preventDefault();move(e.key==='Home'?-4:e.key==='End'?4:[' ','ArrowDown','PageDown'].includes(e.key)?1:-1);},{passive:false});window.addEventListener('resize',()=>{syncStoreCarousel();syncBookingCarousel();updateSectionNav();},{passive:true});root.classList.add('s-x-discrete-sections');root.lang='en';root.dir='ltr';root.classList.remove('is-day-mode');render();syncAllSectionCarouselsImmediately();requestAnimationFrame(()=>updateSectionNav(false));requestAnimationFrame(()=>root.classList.remove('s-x-initializing'));
  language.disabled=false;language.addEventListener('click',e=>{e.stopPropagation();applyLanguage(root.lang==='ar'?'en':'ar');});try{const initialLanguage=localStorage.getItem('ooxme-language');if(initialLanguage==='ar')applyLanguage('ar',{persist:false,emit:false});}catch(_){/* Shared language preference may be unavailable. */}
  root.classList.remove('s-x-discrete-sections');
})();
