const plansCopy={
  en:{
    title:'OOXME Partnership Plans',home:'Home',languageAria:'Switch to Arabic',
    heroLabel:'Partnership Plans',heroHeading:'OOXME Partnership Plans',heroCopy:'Flexible monthly partnerships designed to help businesses build, grow, and lead their markets through strategic business development, brand management, and creative execution.',
    comparisonLabel:'Plan Details',detailsSuffix:'Plan Details',planWord:'Plan',nextPlan:'Next Plan',monthlyInvestment:'Monthly Investment',includes:'Includes',
    includedLabel:'Included in Every Plan',includedHeading:'Always Part of the Partnership',
    noteLabel:'Additional Costs',noteCopy:'Third-party subscription fees such as hosting, domain registration, Google Workspace, Meta Verified, advertising budgets, and other external services are managed by OOXME but billed separately from the partnership plans.',
    ctaHeading:'Ready to Grow Your Business?',ctaCopy:'Choose the partnership that matches your business goals and let OOXME become your long-term business development partner.',ctaPrimary:'Subscribe Now',ctaSecondary:'Contact OOXME',
    plans:[
      ['starter','START','$699/month',[['Brand Management','Brand creation or development'],['Business Development','Monthly consulting & growth planning'],['Social Media Management','Instagram, Facebook & LinkedIn'],['Website','Professional website creation'],['Marketing','Monthly marketing plan'],['HR Support','Basic HR support & recruitment assistance'],['Content Production','4 photo sessions + 4 videos per month'],['Premium Production','Professional editing & interior/product shoots'],['Digital Services','Google Business setup, website launch & business profiles'],['Support','Priority support & monthly review']]],
      ['standard','SCALE','$999/month',[['Brand Management','Advanced brand management'],['Business Development','Bi-weekly consulting & business optimization'],['Social Media Management','Instagram, Facebook & LinkedIn'],['Website','Advanced website with additional pages & features'],['Marketing','Marketing plan + campaign management'],['HR Support','Recruitment + HR documentation'],['Content Production','6 photo sessions + 6 videos per month'],['Premium Production','Professional editing + Drone footage'],['Digital Services','Technical support & optimization'],['Support','High-priority support & bi-weekly review']]],
      ['premium','PREMIUM','$1,499/month',[['Brand Management','Complete brand strategy & management'],['Business Development','Weekly executive consulting & business development'],['Social Media Management','Instagram, Facebook & LinkedIn + advanced strategy'],['Website','Premium website with ongoing improvements'],['Marketing','Full marketing strategy, campaign supervision & reporting'],['HR Support','Complete HR systems & organizational development'],['Content Production','8+ photo sessions + 8+ videos per month'],['Premium Production','Drone footage, professional models, voice-over & premium production'],['Digital Services','Complete digital ecosystem management & business verification support'],['Support','VIP support, weekly meetings & dedicated account manager']]]
    ],
    included:['Brand creation for new businesses or brand development for existing businesses','Instagram, Facebook, and LinkedIn management','Professional photography and videography','Business development consulting','Website creation','Monthly performance review']
  },
  ar:{
    title:'خطط شراكة اوكسوم',home:'الرئيسية',languageAria:'التبديل إلى الإنجليزية',
    heroLabel:'خطط الشراكة',heroHeading:'خطط شراكة اوكسوم',heroCopy:'شراكات شهرية مرنة صُممت لمساعدة الأعمال على البناء والنمو وقيادة أسواقها عبر تطوير الأعمال الاستراتيجي وإدارة العلامة والتنفيذ الإبداعي.',
    comparisonLabel:'تفاصيل الباقة',detailsSuffix:'تفاصيل الباقة',planWord:'باقة',nextPlan:'الباقة التالية',monthlyInvestment:'الاستثمار الشهري',includes:'تشمل',
    includedLabel:'مشمول في كل باقة',includedHeading:'جزء أساسي من كل شراكة',
    noteLabel:'تكاليف إضافية',noteCopy:'تُدار رسوم اشتراكات الجهات الخارجية مثل الاستضافة وتسجيل النطاق وGoogle Workspace وMeta Verified وميزانيات الإعلانات والخدمات الخارجية الأخرى من قبل اوكسوم، لكنها تُفوتر بشكل منفصل عن باقات الشراكة.',
    ctaHeading:'هل أنت مستعد لتنمية أعمالك؟',ctaCopy:'اختر الشراكة التي تناسب أهداف أعمالك واجعل اوكسوم شريكك طويل الأمد في تطوير الأعمال.',ctaPrimary:'اشترك الآن',ctaSecondary:'تواصل مع اوكسوم',
    plans:[
      ['starter','ابدأ','$699/شهريًا',[['إدارة العلامة','إنشاء العلامة أو تطويرها'],['تطوير الأعمال','استشارات شهرية وتخطيط للنمو'],['إدارة وسائل التواصل','Instagram وFacebook وLinkedIn'],['الموقع الإلكتروني','إنشاء موقع احترافي'],['التسويق','خطة تسويق شهرية'],['دعم الموارد البشرية','دعم أساسي للموارد البشرية ومساعدة في التوظيف'],['إنتاج المحتوى','4 جلسات تصوير + 4 فيديوهات شهريًا'],['الإنتاج الاحترافي','مونتاج احترافي وتصوير داخلي وتصوير منتجات'],['الخدمات الرقمية','إعداد Google Business وإطلاق الموقع وملفات الأعمال'],['الدعم','دعم ذو أولوية ومراجعة شهرية']]],
      ['standard','توسّع','$999/شهريًا',[['إدارة العلامة','إدارة متقدمة للعلامة'],['تطوير الأعمال','استشارات نصف شهرية وتحسين الأعمال'],['إدارة وسائل التواصل','Instagram وFacebook وLinkedIn'],['الموقع الإلكتروني','موقع متقدم بصفحات وميزات إضافية'],['التسويق','خطة تسويق وإدارة الحملات'],['دعم الموارد البشرية','التوظيف وتوثيق الموارد البشرية'],['إنتاج المحتوى','6 جلسات تصوير + 6 فيديوهات شهريًا'],['الإنتاج الاحترافي','مونتاج احترافي ولقطات درون'],['الخدمات الرقمية','دعم فني وتحسين مستمر'],['الدعم','دعم عالي الأولوية ومراجعة نصف شهرية']]],
      ['premium','بريميوم','$1,499/شهريًا',[['إدارة العلامة','استراتيجية وإدارة متكاملة للعلامة'],['تطوير الأعمال','استشارات تنفيذية أسبوعية وتطوير للأعمال'],['إدارة وسائل التواصل','Instagram وFacebook وLinkedIn مع استراتيجية متقدمة'],['الموقع الإلكتروني','موقع بريميوم مع تحسينات مستمرة'],['التسويق','استراتيجية تسويق كاملة وإشراف على الحملات وتقارير'],['دعم الموارد البشرية','أنظمة موارد بشرية كاملة وتطوير تنظيمي'],['إنتاج المحتوى','8+ جلسات تصوير + 8+ فيديوهات شهريًا'],['الإنتاج الاحترافي','لقطات درون ونماذج احترافية وتعليق صوتي وإنتاج بريميوم'],['الخدمات الرقمية','إدارة متكاملة للمنظومة الرقمية ودعم توثيق الأعمال'],['الدعم','دعم VIP واجتماعات أسبوعية ومدير حساب مخصص']]]
    ],
    included:['إنشاء علامة للأعمال الجديدة أو تطوير العلامة للأعمال القائمة','إدارة Instagram وFacebook وLinkedIn','تصوير فوتوغرافي وفيديو احترافي','استشارات تطوير الأعمال','إنشاء موقع إلكتروني','مراجعة أداء شهرية']
  }
};

const plansRoot=document.documentElement;
const plansLanguageButton=document.querySelector('.language-toggle');
const plansHomeButton=document.querySelector('.home-control');
const planPagePaths={starter:'plan-starter.html',standard:'plan-standard.html',premium:'plan-plus.html'};
let plansLanguage='en';
try{plansLanguage=localStorage.getItem('ooxme-language')==='ar'?'ar':'en'}catch(error){}

function revealPlanText(){const elements=[...document.querySelectorAll('.text-reveal')];if(!('IntersectionObserver'in window)){elements.forEach((element)=>element.classList.add('is-visible'));return}const observer=new IntersectionObserver((entries)=>entries.forEach((entry)=>entry.target.classList.toggle('is-visible',entry.isIntersecting)),{threshold:.12,rootMargin:'0px 0px -6% 0px'});elements.forEach((element,index)=>{element.style.transitionDelay=`${Math.min(index,8)*55}ms`;observer.observe(element)})}
function getSelectedPlan(copy){return copy.plans.find(([slug])=>slug===document.body.dataset.selectedPlan)||copy.plans[0]}
function renderPlanCards(copy,plan){const [slug,name,price,features]=plan;document.querySelector('[data-plans-table]').innerHTML=`<article class="plan-card text-reveal is-selected" aria-label="${name}"><p class="plan-includes">${copy.includes}</p><ol class="plan-features">${features.map(([title,description])=>`<li><span><strong>${title}</strong><small>${description}</small></span></li>`).join('')}</ol></article>`}
function setPlansLanguage(next){plansLanguage=next;const copy=plansCopy[next];const arabic=next==='ar';const plan=getSelectedPlan(copy);const planIndex=copy.plans.findIndex(([slug])=>slug===plan[0]);const previousPlan=copy.plans[(planIndex-1+copy.plans.length)%copy.plans.length];const nextPlan=copy.plans[(planIndex+1)%copy.plans.length];plansRoot.lang=next;plansRoot.dir=arabic?'rtl':'ltr';document.title=`${plan[1]} ${copy.planWord} — ${arabic?'اوكسوم':'OOXME'}`;document.querySelector('[data-plan-label]').textContent=copy.heroLabel;document.querySelector('[data-plan-heading]').textContent=arabic?`${copy.planWord} ${plan[1]}`:`${plan[1]} ${copy.planWord}`;document.querySelector('[data-plan-copy]').textContent=copy.heroCopy;document.querySelector('[data-comparison-label]').textContent=copy.comparisonLabel;document.querySelector('[data-comparison-heading]').textContent=arabic?`${copy.detailsSuffix} ${plan[1]}`:`${plan[1]} ${copy.detailsSuffix}`;document.querySelector('[data-price-heading]').textContent=plan[2];document.querySelector('[data-included-label]').textContent=copy.includedLabel;document.querySelector('[data-included-heading]').textContent=copy.includedHeading;document.querySelector('[data-note-label]').textContent=copy.noteLabel;document.querySelector('[data-note-copy]').textContent=copy.noteCopy;document.querySelector('[data-cta-heading]').textContent=copy.ctaHeading;document.querySelector('[data-cta-copy]').textContent=copy.ctaCopy;document.querySelector('[data-cta-primary]').textContent=copy.ctaPrimary;document.querySelector('[data-cta-secondary]').textContent=copy.ctaSecondary;const previousLink=document.querySelector('[data-previous-plan]');const nextLink=document.querySelector('[data-next-plan]');previousLink.href=planPagePaths[previousPlan[0]];previousLink.setAttribute('aria-label',`${arabic?'الباقة السابقة':'Previous plan'}: ${previousPlan[1]}`);nextLink.href=planPagePaths[nextPlan[0]];nextLink.setAttribute('aria-label',`${copy.nextPlan}: ${nextPlan[1]}`);document.querySelector('[data-next-plan-name]').textContent=nextPlan[1];plansLanguageButton.setAttribute('aria-label',copy.languageAria);plansHomeButton.setAttribute('aria-label',copy.home);renderPlanCards(copy,plan);document.querySelector('[data-included-list]').innerHTML=copy.included.map((item)=>`<li>${item}</li>`).join('');revealPlanText();try{localStorage.setItem('ooxme-language',next)}catch(error){}}

plansLanguageButton.addEventListener('click',()=>setPlansLanguage(plansLanguage==='en'?'ar':'en'));
plansRoot.classList.add('js');
setPlansLanguage(plansLanguage);
