const portfolioCopy={
  en:{title:'OOXME — Portfolio',navHome:'Home',navWork:'Previous Work',navPlans:'Plans',navServices:'Services',navConsultation:'Consultation',workLabel:'Previous Work',workHeading:'Projects That Speak<br>for Themselves',workCopy:'Showcase selected branding, business development, website, marketing, and creative projects completed by OOXME.',plansLabel:'Plans',plansHeading:'Flexible Monthly<br>Growth Plans',plansCopy:'Choose the partnership level that best matches your business needs.',servicesLabel:'Services',servicesHeading:'Everything Your Business<br>Needs To Grow',servicesCopy:'A connected team of specialists for every important move your business needs to make.',consultationLabel:'Consultation',consultationHeading:'Let’s Build Your<br>Business Together',consultationCopy:'Book a consultation with OOXME to discuss your business, identify opportunities, and create a clear growth strategy.',consultationButton:'Schedule Consultation',project:'Project',plan:'Plan',service:'Service',languageAria:'Switch to Arabic',menuOpen:'Open menu',menuClose:'Close menu'},
  ar:{title:'اوكسوم — المعرض',navHome:'الرئيسية',navWork:'أعمال سابقة',navPlans:'الباقات',navServices:'الخدمات',navConsultation:'استشارة',workLabel:'أعمال سابقة',workHeading:'مشاريع تتحدث<br>عن نفسها',workCopy:'استعرض مشاريع مختارة في العلامات التجارية وتطوير الأعمال والمواقع والتسويق والإبداع أنجزتها اوكسوم.',plansLabel:'الباقات',plansHeading:'باقات نمو شهرية<br>مرنة',plansCopy:'اختر مستوى الشراكة الذي يناسب احتياجات عملك.',servicesLabel:'الخدمات',servicesHeading:'كل ما يحتاجه عملك<br>للنمو',servicesCopy:'فريق متخصص ومترابط لكل خطوة مهمة يحتاجها عملك.',consultationLabel:'استشارة',consultationHeading:'لنبنِ أعمالك<br>معًا',consultationCopy:'احجز استشارة مع اوكسوم لمناقشة عملك وتحديد الفرص وبناء استراتيجية نمو واضحة.',consultationButton:'جدولة استشارة',project:'مشروع',plan:'باقة',service:'خدمة',languageAria:'التبديل إلى الإنجليزية',menuOpen:'فتح القائمة',menuClose:'إغلاق القائمة'}
};
Object.assign(portfolioCopy.en,{seeMore:'See More',seeLess:'Show Less'});
Object.assign(portfolioCopy.ar,{seeMore:'عرض المزيد',seeLess:'عرض أقل'});
Object.assign(portfolioCopy.en,{contactLabel:'Contact',contactHeading:'Let’s Connect',contactCopy:'Have an opportunity, an ambition, or a challenge worth discussing? OOXME is ready to start the conversation.'});
Object.assign(portfolioCopy.ar,{contactLabel:'تواصل',contactHeading:'لنتواصل',contactCopy:'لديك فرصة أو طموح أو تحدٍ يستحق النقاش؟ اوكسوم جاهزة لبدء المحادثة.'});
Object.assign(portfolioCopy.en,{navContact:'Contact'});
Object.assign(portfolioCopy.ar,{navContact:'تواصل'});
const portfolioItems={
  projects:[['albasri-commercial-group','Brands We Managed','علامات تجارية أدرناها'],['alfayha-eyewear','Brands We Created','علامات تجارية أنشأناها'],['viir','Identities & Logos','هويات وشعارات'],['sawa-university','Other','أخرى']],
  plans:[['starter','Starter','البداية','A focused foundation for businesses ready to grow.','أساس متكامل للأعمال المستعدة للنمو.'],['standard','Standard','القياسية','A broader partnership for consistent momentum.','شراكة أوسع لتحقيق نمو مستمر.'],['plus','Premium','بريميوم','A complete, hands-on growth partnership.','شراكة نمو متكاملة بإشراف عملي مباشر.']],
  services:[['business-development','Business Development','تطوير الأعمال'],['brand-strategy','Brand Strategy','استراتيجية العلامة'],['brand-identity','Brand Identity','هوية العلامة'],['brand-management','Brand Management','إدارة العلامة'],['website-design-development','Website Design & Development','تصميم وتطوير المواقع'],['ui-ux-design','UI/UX Design','تصميم تجربة وواجهة المستخدم'],['social-media-management','Social Media Management','إدارة وسائل التواصل'],['content-creation','Content Creation','صناعة المحتوى'],['photography','Photography','التصوير الفوتوغرافي'],['videography','Videography','إنتاج الفيديو'],['drone-production','Drone Production','إنتاج الدرون'],['interior-photography','Interior Photography','تصوير المساحات الداخلية'],['product-photography','Product Photography','تصوير المنتجات'],['motion-graphics','Motion Graphics','الرسوم المتحركة'],['graphic-design','Graphic Design','التصميم الجرافيكي'],['digital-marketing','Digital Marketing','التسويق الرقمي'],['seo','SEO','تحسين محركات البحث'],['advertising-campaigns','Advertising Campaigns','الحملات الإعلانية'],['ai-integration','AI Integration','تكامل الذكاء الاصطناعي'],['business-consultation','Business Consultation','استشارات الأعمال']]
};
const portfolioRoot=document.documentElement;
document.querySelectorAll('[data-current-year]').forEach((element)=>{element.textContent=new Date().getFullYear()});
const portfolioMenu=document.querySelector('.site-menu');
const portfolioMenuButton=document.querySelector('.menu-toggle');
const portfolioLanguageButton=document.querySelector('.language-toggle');
const servicesToggle=document.querySelector('[data-services-toggle]');
let portfolioLanguage='en';
let servicesExpanded=false;
try{portfolioLanguage=localStorage.getItem('ooxme-language')==='ar'?'ar':'en'}catch(error){}

function renderCards(selector,items,type,language){const copy=portfolioCopy[language];document.querySelector(selector).innerHTML=items.map(([slug,en,ar])=>`<a class="content-card ${type==='plan'?'plan-preview ':''}text-reveal" href="${type}-${slug}.html"><span class="card-copy"><p class="card-label">${copy[type]}</p><span class="card-line"><h3 class="card-title">${language==='en'?en:ar}</h3><span class="card-arrow" aria-hidden="true"></span></span></span></a>`).join('')}
function setPortfolioLanguage(next){portfolioLanguage=next;const copy=portfolioCopy[next];portfolioRoot.lang=next;portfolioRoot.dir=next==='ar'?'rtl':'ltr';document.title=copy.title;document.querySelectorAll('[data-i18n]').forEach((element)=>{element.innerHTML=copy[element.dataset.i18n]});portfolioLanguageButton.setAttribute('aria-label',copy.languageAria);renderCards('.project-grid',portfolioItems.projects,'project',next);renderCards('.plan-grid',portfolioItems.plans,'plan',next);renderCards('.service-grid',servicesExpanded?portfolioItems.services:portfolioItems.services.slice(0,5),'service',next);servicesToggle.textContent=copy[servicesExpanded?'seeLess':'seeMore'];servicesToggle.setAttribute('aria-expanded',String(servicesExpanded));setPlanFocus();revealText();try{localStorage.setItem('ooxme-language',next)}catch(error){}}
function setPortfolioMenu(open){portfolioMenu.classList.toggle('is-open',open);portfolioMenuButton.setAttribute('aria-expanded',String(open));portfolioMenuButton.setAttribute('aria-label',portfolioCopy[portfolioLanguage][open?'menuClose':'menuOpen']);document.body.classList.toggle('menu-open',open)}
let revealObserver;
let planFocusObserver;
function setPlanFocus(){if(planFocusObserver)planFocusObserver.disconnect();const cards=[...document.querySelectorAll('.plan-preview')];if(!('IntersectionObserver'in window)){cards.forEach((card,index)=>card.classList.toggle('is-focused',index===0));return}planFocusObserver=new IntersectionObserver((entries)=>entries.forEach((entry)=>entry.target.classList.toggle('is-focused',entry.isIntersecting)),{root:document.querySelector('.plan-grid'),threshold:.68});cards.forEach((card)=>planFocusObserver.observe(card))}
function revealText(){if(revealObserver)revealObserver.disconnect();const elements=[...document.querySelectorAll('.text-reveal')];elements.forEach((element,index)=>{element.style.transitionDelay=`${Math.min(index%6,5)*55}ms`});if(!('IntersectionObserver'in window)){elements.forEach((element)=>element.classList.add('is-visible'));return}revealObserver=new IntersectionObserver((entries)=>entries.forEach((entry)=>entry.target.classList.toggle('is-visible',entry.isIntersecting)),{threshold:.14,rootMargin:'0px 0px -7% 0px'});elements.forEach((element)=>revealObserver.observe(element))}
portfolioMenuButton.addEventListener('click',()=>setPortfolioMenu(!portfolioMenu.classList.contains('is-open')));
portfolioLanguageButton.addEventListener('click',()=>setPortfolioLanguage(portfolioLanguage==='en'?'ar':'en'));
servicesToggle.addEventListener('click',()=>{servicesExpanded=!servicesExpanded;setPortfolioLanguage(portfolioLanguage)});
portfolioMenu.querySelectorAll('a').forEach((link)=>link.addEventListener('click',()=>setPortfolioMenu(false)));
document.addEventListener('keydown',(event)=>{if(event.key==='Escape')setPortfolioMenu(false)});
portfolioRoot.classList.add('js');setPortfolioLanguage(portfolioLanguage);
