const crypto = require('crypto');
const { json, methodNotAllowed, readJson } = require('../_lib/http');
const { query } = require('../_lib/db');
const { decimal, integer, jsonArray, nullableText, text } = require('../_lib/os-helpers');
const { requireAdmin, requireCsrf } = require('../_lib/os-auth');
const { recordAudit, setRequestId } = require('../_lib/os-audit');
const { begin: beginIdempotency, complete: completeIdempotency } = require('../_lib/os-idempotency');

const parseArray = (value) => Array.isArray(value) ? value : [];
const serialize = (row) => {
  const used = Number(row.usage_count) || 0; const limit = row.total_usage_limit == null ? null : Number(row.total_usage_limit);
  const expired = row.status !== 'active' || (row.starts_at && new Date(row.starts_at).getTime() > Date.now()) || (row.ends_at && new Date(row.ends_at).getTime() <= Date.now()) || (limit != null && used >= limit);
  const services = parseArray(row.service_restrictions); const durations = parseArray(row.duration_restrictions).map(Number).filter(Number.isFinite);
  return { id: row.id, code: row.code_normalized, status: expired ? 'inactive' : 'active', usageCount: used, availableCount: limit == null ? null : Math.max(0, limit - used), totalUsageLimit: limit, perCustomerLimit: row.per_customer_limit == null ? null : Number(row.per_customer_limit), discountType: row.discount_type, discountValue: Number(row.discount_value), currency: row.currency || 'USD', discount: row.discount_type === 'percentage' ? `${Number(row.discount_value)}%` : `${Number(row.discount_value)} ${row.currency || ''}`.trim(), serviceRestrictions: services, durationRestrictions: durations, appliesTo: `${services.length ? services.join(', ') : 'all consultations'}${durations.length ? ` · ${durations.join(', ')} min` : ''}`, startsAt: row.starts_at, endsAt: row.ends_at, campaignSource: row.campaign_source || '', version: row.version || 1, usageHistory: row.usage_history || [] };
};
const select = `SELECT p.id,p.code_normalized,p.status,p.campaign_source,p.starts_at,p.ends_at,p.total_usage_limit,p.per_customer_limit,p.service_restrictions,p.duration_restrictions,p.discount_type,p.discount_value,p.currency,p.version, COUNT(r.id) FILTER (WHERE r.status = 'redeemed' OR (r.status = 'pending' AND r.reservation_expires_at > now()))::int AS usage_count, COALESCE((SELECT json_agg(json_build_object('status', rh.status, 'createdAt', rh.created_at, 'redeemedAt', rh.redeemed_at) ORDER BY rh.created_at DESC) FROM promotion_redemptions rh WHERE rh.promotion_id = p.id), '[]'::json) AS usage_history FROM promotions p LEFT JOIN promotion_redemptions r ON r.promotion_id = p.id WHERE p.status <> 'archived' GROUP BY p.id ORDER BY p.created_at DESC,p.code_normalized ASC`;
const fields = (body) => {
  const code = text(body.code).toUpperCase(); if (!/^[A-Z0-9_-]{2,64}$/.test(code)) throw Object.assign(new Error('promo_code_invalid'), { status: 400 });
  const discountType = body.discountType === 'fixed' ? 'fixed' : 'percentage'; const discountValue = decimal(body.discountValue); if (discountValue == null || discountValue < 0 || (discountType === 'percentage' && discountValue > 100)) throw Object.assign(new Error('discount_invalid'), { status: 400 });
  const limit = integer(body.totalUsageLimit); const customerLimit = integer(body.perCustomerLimit); if ((limit != null && limit < 0) || (customerLimit != null && customerLimit < 0)) throw Object.assign(new Error('usage_limit_invalid'), { status: 400 });
  let startsAt = null; let endsAt = null; try { startsAt = body.startsAt ? new Date(body.startsAt).toISOString() : null; endsAt = body.endsAt ? new Date(body.endsAt).toISOString() : null; } catch (_) { throw Object.assign(new Error('validity_invalid'), { status: 400 }); } if (startsAt && endsAt && new Date(endsAt) <= new Date(startsAt)) throw Object.assign(new Error('validity_invalid'), { status: 400 });
  return { code, discountType, discountValue, currency: nullableText(body.currency)?.toUpperCase().slice(0, 3) || null, startsAt, endsAt, limit, customerLimit, services: jsonArray(body.serviceRestrictions), durations: jsonArray(body.durationRestrictions).map(Number).filter(Number.isInteger), campaignSource: nullableText(body.campaignSource) || 'promo_input', status: ['active', 'inactive', 'archived'].includes(body.status) ? body.status : 'active' };
};

module.exports = async (request, response) => {
  setRequestId(request, response); response.setHeader('Cache-Control', 'no-store'); if (!['GET', 'POST'].includes(request.method)) return methodNotAllowed(response, ['GET', 'POST']);
  try {
    const session = await requireAdmin(request);
    if (request.method === 'GET') { const result = await query(select); return json(response, 200, { success: true, data: { promoCodes: result.rows.map(serialize) } }); }
    requireCsrf(request, session); const body = await readJson(request); const action = text(body.action);
    if (action === 'delete' || action === 'archive') { const id = text(body.id); const version = integer(body.version); const result = await query(`UPDATE promotions SET status='archived',updated_at=now(),version=version+1 WHERE id=$1 AND status <> 'archived' AND ($2::int IS NULL OR version = $2) RETURNING id`, [id, version]); if (!result.rowCount) throw Object.assign(new Error(version == null ? 'promo_code_not_found' : 'promo_code_conflict'), { status: version == null ? 404 : 409 }); await recordAudit({ request, action: 'archive', resourceType: 'promo_code', resourceId: id }).catch(() => undefined); return json(response, 200, { success: true }); }
    if (action === 'toggle') { const id = text(body.id); const version = integer(body.version); const result = await query(`UPDATE promotions SET status=CASE WHEN status='active' THEN 'inactive' ELSE 'active' END,updated_at=now(),version=version+1 WHERE id=$1 AND status <> 'archived' AND ($2::int IS NULL OR version = $2) RETURNING id`, [id, version]); if (!result.rowCount) throw Object.assign(new Error(version == null ? 'promo_code_not_found' : 'promo_code_conflict'), { status: version == null ? 404 : 409 }); await recordAudit({ request, action: 'toggle', resourceType: 'promo_code', resourceId: id }).catch(() => undefined); return json(response, 200, { success: true }); }
    const value = fields(body);
    if (action === 'create') { const idempotency = await beginIdempotency(request, 'promo_code:create', body); if (idempotency?.replay) return json(response, idempotency.status, idempotency.body); const result = await query(`INSERT INTO promotions (id,code_normalized,status,campaign_source,starts_at,ends_at,total_usage_limit,per_customer_limit,service_restrictions,duration_restrictions,discount_type,discount_value,currency) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) RETURNING *`, [crypto.randomUUID(), value.code, value.status, value.campaignSource, value.startsAt, value.endsAt, value.limit, value.customerLimit, JSON.stringify(value.services), JSON.stringify(value.durations), value.discountType, value.discountValue, value.currency]); const bodyResult = { success: true, data: { promoCode: serialize(result.rows[0]) } }; await completeIdempotency(idempotency, { status: 201, body: bodyResult, resourceType: 'promo_code', resourceId: result.rows[0].id }); await recordAudit({ request, action: 'create', resourceType: 'promo_code', resourceId: result.rows[0].id }).catch(() => undefined); return json(response, 201, bodyResult); }
    if (action === 'update') { const id = text(body.id); const version = integer(body.version); if (!id || version == null) throw Object.assign(new Error('id_and_version_required'), { status: 400 }); const result = await query(`UPDATE promotions SET code_normalized=$2,status=$3,campaign_source=$4,starts_at=$5,ends_at=$6,total_usage_limit=$7,per_customer_limit=$8,service_restrictions=$9,duration_restrictions=$10,discount_type=$11,discount_value=$12,currency=$13,updated_at=now(),version=version+1 WHERE id=$1 AND version=$14 AND status <> 'archived' RETURNING *`, [id, value.code, value.status, value.campaignSource, value.startsAt, value.endsAt, value.limit, value.customerLimit, JSON.stringify(value.services), JSON.stringify(value.durations), value.discountType, value.discountValue, value.currency, version]); if (!result.rowCount) throw Object.assign(new Error('promo_code_conflict_or_not_found'), { status: 409 }); await recordAudit({ request, action: 'update', resourceType: 'promo_code', resourceId: id }).catch(() => undefined); return json(response, 200, { success: true, data: { promoCode: serialize(result.rows[0]) } }); }
    throw Object.assign(new Error('promo_code_action_invalid'), { status: 400 });
  } catch (error) { const status = Number(error.status) || 503; if (status >= 500) console.error('OS promo codes request failed', error.code || error.message); return json(response, status, { success: false, error: status >= 500 ? 'promo_codes_unavailable' : error.message }); }
};
